name = "asado-invoice"
type = "javascript"
workers_dev = true
main = "src/index.js"

[build]
command = "echo 'Building...'"

[env.production]
routes = [
  { pattern = "asado-invoice.mind-ppj.workers.dev/*", zone_name = "mind-ppj.workers.dev" }
]

[[observability.enabled]]
enabled = true
